name = "gattai-nanpure"
compatibility_date = "2024-11-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "QUOTA"
id = "e74451c9be784ff380e1039aaa03794e"
# preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # ローカル用を分けるなら

[vars]
DAILY_LIMIT = "20"
DAILY_LIMIT_WITH_AD = "100"
GEN_TIMEOUT_MS = "3500"
MAX_BOARDS = "40"
GEN_RETRY = "3"
