name = "gattai-nanpure"
compatibility_date = "2024-11-01"
pages_build_output_dir = "."

# KV は [[kv_namespaces]] で宣言する（配列リテラルではなくテーブル配列）
[[kv_namespaces]]
binding = "QUOTA"
id = "e74451c9be784ff380e1039aaa03794e"

[[kv_namespaces]]
binding = "MY_KV"
id = "e74451c9be784ff380e1039aaa03794e"

[vars]
DAILY_LIMIT = "20"
DAILY_LIMIT_WITH_AD = "100"
GEN_TIMEOUT_MS = "3500"
MAX_BOARDS = "40"
GEN_RETRY = "3"
